services:
  llmproxy:
    build:
      context: .
      dockerfile: LLMProxy/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    expose:
      - "8080"
    networks:
      - tailscale-net
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--hostname=llmproxy
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/https.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./https.json:/config/https.json:ro
    networks:
      - tailscale-net
    restart: unless-stopped

networks:
  tailscale-net:
    driver: bridge

volumes:
  tailscale-state:
